"""baseline_schema

Revision ID: d437eb92d569
Revises: 
Create Date: 2026-05-14 09:21:34.324205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd437eb92d569'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('expected_status_code', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('endpoints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_endpoints_id'), ['id'], unique=False)

    op.create_table('checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('expected_status_code', sa.Integer(), nullable=False),
    sa.Column('actual_status_code', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checks_id'), ['id'], unique=False)

    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incidents_id'), ['id'], unique=False)
        batch_op.create_index('uq_open_incident_endpoint', ['endpoint_id'], unique=True, sqlite_where=sa.text("status = 'open'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index('uq_open_incident_endpoint', sqlite_where=sa.text("status = 'open'"))
        batch_op.drop_index(batch_op.f('ix_incidents_id'))

    op.drop_table('incidents')
    with op.batch_alter_table('checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checks_id'))

    op.drop_table('checks')
    with op.batch_alter_table('endpoints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_endpoints_id'))

    op.drop_table('endpoints')
    # ### end Alembic commands ###
